name: "GitHub Metrics Report"
description: "Posts GitHub metrics to an Endpoint for tracking metrics over time"

inputs:
  github_personal_access_token:
    description: "Provide GitHub Personal Access Token"
    required: true
  github_repo:
    description: "GitHub owner/repo name"
    required: true
  reporting_endpoint_url:
    description: "Azure Function App reporting endpoint url"
    required: true
  reporting_endpoint_key:
    description: "Azure Function App reporting endpoint key"
    required: true
  reporting_group:
    description: "Reporting group or team name"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_personal_access_token }} 
    - ${{ inputs.github_repo }} 
    - ${{ inputs.reporting_endpoint_url }} 
    - ${{ inputs.reporting_endpoint_key }} 
    - ${{ inputs.reporting_group }}